version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - coinswarm
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == vps0
      restart_policy:
        condition: on-failure
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    networks:
      - elk
      - coinswarm
    ports:
      - "5601:5601"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == vps0
      restart_policy:
        condition: on-failure
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.4
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - elk
      - coinswarm
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.hostname == vps0
      restart_policy:
        condition: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.4
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk
      - coinswarm
    user: root
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    depends_on:
      - logstash
    configs:
      - source: filebeat_config
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true

networks:
  coinswarm:
    external: true
  elk:
    driver: overlay

volumes:
  esdata:
    driver: local

configs:
  filebeat_config:
    file: ./filebeat.yml 