version: '3.7'

services:
  elasticsearch:
    image: elastic/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node        # Chạy single-node
      - cluster.name=elk-cluster          # Tên cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # Heap size 512MB
      - "xpack.security.enabled=false"    # Tắt security để đơn giản hóa
      - bootstrap.memory_lock=true        # Khóa bộ nhớ
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk_network
    ports:
      - "9200:9200"
    deploy:
      placement:
        constraints:
          - node.hostname == vps0
      replicas: 1
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  kibana:
    image: elastic/kibana:8.17.4
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - "xpack.security.enabled=false"
      - "NODE_OPTIONS=--max-old-space-size=1024"
    networks:
      - elk_network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints:
          - node.hostname == vps0
      replicas: 1
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 180s

  logstash:
    image: elastic/logstash:8.17.4
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks:
      - elk_network
    ports:
      - "5044:5044"
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints:
          - node.hostname == vps0
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  filebeat:
    image: elastic/filebeat:8.17.4
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - elk_network
    depends_on:
      - logstash
    deploy:
      placement:
        constraints:
          - node.hostname == vps0
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

volumes:
  elasticsearch-data:

networks:
  elk_network:
    driver: overlay
