filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.message_key: log
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - add_fields:
        target: docker
        fields:
          swarm_stack: ${SWARM_STACK_NAME:dockercoins}
    - drop_event:
        when:
          not:
            or:
              - equals:
                  container.image.name: "${USERNAME:-mrnam}/worker"
              - equals:
                  container.image.name: "${USERNAME:-mrnam}/webui"
              - equals:
                  container.image.name: "${USERNAME:-mrnam}/hasher"
              - equals:
                  container.image.name: "${USERNAME:-mrnam}/rng"

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

setup.ilm.enabled: false
setup.template.enabled: false

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0640 