global:
  scrape_interval: 15s  # Thời gian thu thập metrics (15 giây)
  evaluation_interval: 15s  # Thời gian đánh giá rules (15 giây)

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus tự thu thập metrics của chính nó

  - job_name: 'filebeat'
    static_configs:
      - targets: ['filebeat:9400']  # Giả sử Filebeat có exporter metrics ở cổng 9400

  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']  # Logstash exporter mặc định ở cổng 9600

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9100']  # Cần exporter cho Elasticsearch
